// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkgqV7qTBF-Fh7ZgT2Sponbbs2yJ-OvdI',
    appId: '1:679874674301:web:300ddaf8dd57d6db697b14',
    messagingSenderId: '679874674301',
    projectId: 'healthsyncycare',
    authDomain: 'healthsyncycare.firebaseapp.com',
    storageBucket: 'healthsyncycare.appspot.com',
    measurementId: 'G-5SV394NFTD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-6l44aSSzRICm9K7Ayt2CCfTXayXgtIY',
    appId: '1:679874674301:android:9c157be43474e978697b14',
    messagingSenderId: '679874674301',
    projectId: 'healthsyncycare',
    storageBucket: 'healthsyncycare.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkGbHMBd5hjaUQuc8OdzM1ltsiUob6RMo',
    appId: '1:679874674301:ios:906bd93a763147c9697b14',
    messagingSenderId: '679874674301',
    projectId: 'healthsyncycare',
    storageBucket: 'healthsyncycare.appspot.com',
    iosBundleId: 'com.example.healthsyncycare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkGbHMBd5hjaUQuc8OdzM1ltsiUob6RMo',
    appId: '1:679874674301:ios:906bd93a763147c9697b14',
    messagingSenderId: '679874674301',
    projectId: 'healthsyncycare',
    storageBucket: 'healthsyncycare.appspot.com',
    iosBundleId: 'com.example.healthsyncycare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkgqV7qTBF-Fh7ZgT2Sponbbs2yJ-OvdI',
    appId: '1:679874674301:web:300ddaf8dd57d6db697b14',
    messagingSenderId: '679874674301',
    projectId: 'healthsyncycare',
    authDomain: 'healthsyncycare.firebaseapp.com',
    storageBucket: 'healthsyncycare.appspot.com',
    measurementId: 'G-5SV394NFTD',
  );

}